Hello Rosetta Administrators,

There was an exception %(exception)s when handling
export of %(pofile)s (entry ID: #%(exportid)d).

The traceback was:

%(traceback)s


If the problem repeats itself, it's quite likely a persistent problem
with particular entry in the translation export queue, so you should
investigate and fix it.

Thank you,
Rosetta Export Queue script
